#cloud-config

# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://about.gitlab.com/install/?version=ce
# https://gitlab.com/gitlab-org/gitlab-foss/

write_files:
  - path: /var/lib/docker/daemon.json
    permissions: 0644
    owner: root
    content: |
      {
        "live-restore": true,
        "storage-driver": "overlay2",
        "log-opts": {
          "max-size": "1024m"
        }
      }

  %{~ for disk in disks ~}
  # units used to mount and format disks
  - path: /etc/systemd/system/gitlab-disk-${disk}.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Gitlab data disk for ${disk}
      ConditionPathExists=/dev/disk/by-id/google-${disk}
      Before=gitlab.service
      [Service]
      Type=oneshot
      ExecStart=/bin/mkdir -p /mnt/disks/gitlab-${disk}
      ExecStart=/bin/bash -c \
        "/bin/lsblk -fn -o FSTYPE \
          /dev/disk/by-id/google-${disk} |grep ext4 \
        || mkfs.ext4 -m 0 -F -E lazy_itable_init=0,lazy_journal_init=0,discard \
          /dev/disk/by-id/google-${disk}"
      ExecStart=/bin/bash -c \
        "mount |grep /mnt/disks/gitlab-${disk} \
        || mount -t ext4 /dev/disk/by-id/google-${disk} /mnt/disks/gitlab-${disk}"
      ExecStart=/sbin/resize2fs /dev/disk/by-id/google-${disk}
      RemainAfterExit=true
  %{~ endfor ~}

  %{~ if env_file != null ~}
  # gitlab environment variables file
  - path: /run/gitlab-env.list
    permissions: 0644
    owner: root
    content: |
      ${indent(6, env_file)}
  %{ endif ~}

  # gitlab ce container service
  - path: /etc/systemd/system/gitlab.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Start Gitlab CE container
      After=gcr-online.target docker.socket%{ for disk in disks } gitlab-disk-${disk}.service %{~ endfor }
      Wants=gcr-online.target docker.socket docker-events-collector.service%{ for disk in disks } gitlab-disk-${disk}.service %{~ endfor }
      [Service]
      %{~ for s in create_sources ~}
      ExecStartPre=/bin/mkdir -p ${s}
      %{~ endfor ~}
      ExecStart=/usr/bin/docker run --rm \
        %{~ for k, v in env ~}
        --env ${k}="${v}" \
        %{~ endfor ~}
        %{~ if env_file != null ~}
        --env-file /run/gitlab-env.list \
        %{~ endif ~}
        %{~ if hostname != null ~}
        --hostname gitlab.example.com \
        %{~ endif ~}
        --log-driver=gcplogs \
        --name=gitlab-ce \
        --network host \
        --shm-size 256m \
        %{~ for mount in mounts ~}
        --volume ${mount.source}:${mount.mountpoint} \
        %{~ endfor ~}
        ${image}
      ExecStop=/usr/bin/docker stop gitlab-ce

bootcmd:
  - systemctl start node-problem-detector

runcmd:
  - iptables -I INPUT 1 -p tcp -m tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT
  - iptables -I INPUT 1 -p tcp -m tcp --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT
  - systemctl daemon-reload
  - systemctl start gitlab
