#cloud-config

# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://about.gitlab.com/install/?version=ce
# https://gitlab.com/gitlab-org/gitlab-foss/

users:
  - name: nginx
    uid: 2000

write_files:
  - path: /var/lib/docker/daemon.json
    permissions: 0644
    owner: root
    content: |
      {
        "live-restore": true,
        "storage-driver": "overlay2",
        "log-opts": {
          "max-size": "1024m"
        }
      }

  # gitlab data disk service
  - path: /etc/systemd/system/gitlab-data.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Gitlab data disk
      ConditionPathExists=/dev/disk/by-id/google-data
      Before=gitlab.service
      [Service]
      Type=oneshot
      ExecStart=/bin/mkdir -p /mnt/disks/gitlab-data
      ExecStart=/bin/bash -c \
        "/bin/lsblk -fn -o FSTYPE \
          /dev/disk/by-id/google-data |grep ext4 \
        || mkfs.ext4 -m 0 -F -E lazy_itable_init=0,lazy_journal_init=0,discard \
          /dev/disk/by-id/google-data"
      ExecStart=/bin/bash -c \
        "mount |grep /mnt/disks/gitlab-data \
        || mount -t ext4 /dev/disk/by-id/google-data /mnt/disks/gitlab-data"
      ExecStart=/sbin/resize2fs /dev/disk/by-id/google-data
      RemainAfterExit=true

%{~ if length(env) > 0 }
  # gitlab environment variables file
  - path: /run/gitlab-env.list
    permissions: 0644
    owner: root
    content: |
      %{~ for k, v in env ~}
      ${k} = "${v}"
      %{~ endfor ~}
%{ endif ~}

  # gitlab ce container service
  - path: /etc/systemd/system/gitlab.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Start Gitlab CE container
      After=gcr-online.target docker.socket gitlab-data.service
      Wants=gcr-online.target docker.socket docker-events-collector.service gitlab-data.service
      [Service]
      ExecStart=/usr/bin/docker run --rm --name=gitlab-ce  \
        --log-driver=gcplogs --network host \
        --hostname gitlab.example.com \
        --shm-size 256m \
        -v /mnt/disks/gitlab-data/config:/etc/gitlab \
        -v /mnt/disks/gitlab-data/logs:/var/log/gitlab \
        -v /mnt/disks/gitlab-data/data:/var/opt/gitlab \
%{~ if length(env) > 0 }
        --env-file /run/gitlab-env.list \
%{ endif ~}
        ${image}
      ExecStop=/usr/bin/docker stop gitlab-ce

bootcmd:
  - systemctl start node-problem-detector

runcmd:
  - iptables -I INPUT 1 -p tcp -m tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT
  - iptables -I INPUT 1 -p tcp -m tcp --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT
  - systemctl daemon-reload
  - systemctl start gitlab
